import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Platform",
      collapsed: false,
      items: [
        "platform/overview",
        "platform/architecture",
        "platform/ingress-and-networking",
        "platform/security-model",
        "platform/authentication-flow",
        "platform/configuration-management",
        "platform/environments",
      ],
    },
    {
      type: "category",
      label: "Services",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Analytics Service",
          items: [
            "services/analytics/overview",
            "services/analytics/architecture",
            "services/analytics/api-contract",
            "services/analytics/configuration",
            "services/analytics/deployment",
            "services/analytics/security",
            "services/analytics/failure-modes",
          ],
        },
        {
          type: "category",
          label: "API Gateway",
          items: [
            "services/apigateway/overview",
            "services/apigateway/architecture",
            "services/apigateway/api-contract",
            "services/apigateway/configuration",
            "services/apigateway/deployment",
            "services/apigateway/security",
            "services/apigateway/failure-modes",
          ],
        },
        {
          type: "category",
          label: "Auth Service",
          items: [
            "services/auth/overview",
            "services/auth/architecture",
            "services/auth/api-contract",
            "services/auth/configuration",
            "services/auth/deployment",
            "services/auth/security",
            "services/auth/failure-modes",
          ],
        },
        {
          type: "category",
          label: "Portfolio Service",
          items: [
            "services/portfolio/overview",
            "services/portfolio/architecture",
            "services/portfolio/api-contract",
            "services/portfolio/configuration",
            "services/portfolio/deployment",
            "services/portfolio/security",
            "services/portfolio/failure-modes",
          ],
        },
        {
          type: "category",
          label: "RTTM Service",
          items: [
            "services/rttm/overview",
            "services/rttm/architecture",
            "services/rttm/api-contract",
            "services/rttm/configuration",
            "services/rttm/deployment",
            "services/rttm/security",
            "services/rttm/failure-modes",
          ],
        },
        {
          type: "category",
          label: "Simulation Service",
          items: [
            "services/simulation/overview",
            "services/simulation/architecture",
            "services/simulation/api-contract",
            "services/simulation/configuration",
            "services/simulation/deployment",
            "services/simulation/security",
            "services/simulation/failure-modes",
          ],
        },
        {
          type: "category",
          label: "Transactional Service",
          items: [
            "services/transactional/overview",
            "services/transactional/architecture",
            "services/transactional/api-contract",
            "services/transactional/configuration",
            "services/transactional/deployment",
            "services/transactional/security",
            "services/transactional/failure-modes",
          ],
        },
        {
          type: "category",
          label: "Validation Service",
          items: [
            "services/validation/overview",
            "services/validation/architecture",
            "services/validation/api-contract",
            "services/validation/configuration",
            "services/validation/deployment",
            "services/validation/security",
            "services/validation/failure-modes",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Frontend",
      collapsed: false,
      items: [
        "frontend/overview",
        "frontend/configuration",
        "frontend/auth-integration",
        "frontend/websocket-integration",
        "frontend/common-issues",
      ],
    },
    {
      type: "category",
      label: "Infrastructure",
      collapsed: false,
      items: [
        "infrastructure/eks",
        "infrastructure/ingress",
        "infrastructure/networking",
        "infrastructure/secrets-management",
        "infrastructure/scaling-and-upgrades",
      ],
    },
    {
      type: "category",
      label: "Operations",
      collapsed: false,
      items: [
        "operations/deployment-guide",
        "operations/monitoring",
        "operations/debugging",
        "operations/runbooks",
        "operations/incident-response",
      ],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: false,
      items: [
        "reference/endpoints",
        "reference/ports-and-protocols",
        "reference/glossary",
      ],
    },
  ],
};

export default sidebars;
